import type { DemoTask } from "./model.ts";

/** Fixed, fictional comparison data. Never copied from an authenticated provider. */
export const DEMO_DAY = "Monday, September 21, 2026";
export const sources = {
  byu: {
    name: "BYU Canvas",
    account: "learner@example.edu",
    lastSuccess: "Sep 21, 6:00 AM MDT",
    capability: "Read-only demo snapshot",
  },
  aws: {
    name: "AWS Canvas",
    account: "cloud-learner@example.edu",
    lastSuccess: "Sep 21, 6:02 AM MDT",
    capability: "Read-only demo snapshot",
  },
  manual: {
    name: "Manual capture",
    account: "Jordan Demo · local workspace",
    lastSuccess: "Not synchronized",
    capability: "Local planning only",
  },
} as const;

const task = (value: Omit<DemoTask, "done" | "notes">): DemoTask => ({
  ...value,
  done: false,
  notes: "",
});
export const initialTasks: DemoTask[] = [
  task({
    id: "equipment",
    area: "school",
    course: "IS 402",
    title: "Model the campus equipment checkout",
    source: "byu",
    resource: "O’Reilly · Chapter 4",
    due: "Tonight · 11:59 PM",
    estimate: 75,
    kind: "Assignment",
    attention: "Due today",
  }),
  task({
    id: "cloud-network",
    area: "school",
    course: "IS 404",
    title: "Build a secure cloud network",
    source: "aws",
    resource: "AWS lab · Module 3",
    due: "Tomorrow · 5:00 PM",
    estimate: 90,
    kind: "Assignment",
  }),
  task({
    id: "scrum",
    area: "school",
    course: "IS 401",
    title: "Read Scrum chapters 2–3",
    source: "byu",
    resource: "Physical Scrum book",
    due: "Wed, Sep 23",
    estimate: 30,
    kind: "Reading",
  }),
  task({
    id: "ethics",
    area: "school",
    course: "IS 403",
    title: "Complete the data ethics reading",
    source: "byu",
    resource: "MyEducator · Chapter 2",
    due: "Thu, Sep 24",
    estimate: 40,
    kind: "Reading",
  }),
  task({
    id: "feedback",
    area: "school",
    course: "IS 403",
    title: "Practice the feedback conversation",
    source: "byu",
    resource: "Xenos · Exercise link",
    due: "Fri, Sep 25",
    estimate: 25,
    kind: "Assignment",
  }),
  task({
    id: "communication",
    area: "school",
    course: "IS 403",
    title: "Read the assigned communication chapter",
    source: "manual",
    resource: "How to Win Friends · PDF",
    due: "No verified deadline",
    estimate: null,
    kind: "Reading",
    attention: "Needs review",
  }),
  task({
    id: "ta-office",
    area: "ta",
    title: "Prepare office hours",
    due: "Tomorrow · 2:00 PM",
    source: "manual",
    resource: "TA preparation",
    estimate: 30,
    kind: "Task",
  }),
  task({
    id: "ta-rubric",
    area: "ta",
    title: "Review the project rubric",
    due: "Wednesday",
    source: "manual",
    resource: "TA preparation",
    estimate: 25,
    kind: "Task",
  }),
  task({
    id: "work-outline",
    area: "work",
    title: "Prepare follow-up talking points",
    due: "Tomorrow",
    source: "manual",
    resource: "Fictional work task",
    estimate: 20,
    kind: "Task",
  }),
  task({
    id: "work-review",
    area: "work",
    title: "Review this week’s outreach plan",
    due: "Wednesday",
    source: "manual",
    resource: "Fictional work task",
    estimate: 30,
    kind: "Task",
  }),
  task({
    id: "career-application",
    area: "career",
    title: "Prepare a product internship application",
    due: "Friday · Sep 25",
    source: "manual",
    resource: "Fictional opportunity",
    estimate: 60,
    kind: "Task",
  }),
  task({
    id: "career-interview",
    area: "career",
    title: "Practice product interview questions",
    due: "Wednesday",
    source: "manual",
    resource: "Interview preparation",
    estimate: 30,
    kind: "Task",
  }),
  task({
    id: "project-case",
    area: "projects",
    title: "Draft the portfolio case study",
    due: "Thursday · Sep 24",
    source: "manual",
    resource: "Portfolio",
    estimate: 45,
    kind: "Task",
  }),
];

export const schedule = [
  {
    time: "10:00",
    title: "Core class",
    detail: "School calendar · 60 min",
    free: false,
  },
  {
    time: "12:00",
    title: "Lunch & reset",
    detail: "Personal calendar · 60 min",
    free: false,
  },
  {
    time: "13:00",
    title: "Available · 2 hours",
    detail: "School + personal calendars only",
    free: true,
  },
  {
    time: "16:00",
    title: "Project check-in",
    detail: "School calendar · 30 min",
    free: false,
  },
];
